/**   Description :   creating another class to perform overriding
*
*     Created By  :   Sudheer Kumar Shakya
*
*     Arguments   :   None
*
*     Return      :   void
*
*     Revision log:   V_1.0 - Created  - Sudheer Kumar Shakya - Date-04/07/2022
*                     V_1.1 - Modified - Sudheer Kumar Shakya- Date -04/07/2022
* 
**/ 
public class Override2 extends Overriding { 

    /**   Description :   creating a method
    *
    *     Created By  :   Sudheer Kumar Shakya
    *
    *     Arguments   :   None
    *
    *     Return      :   void
    *
    *     Revision log:   V_1.0 - Created  - Sudheer Kumar Shakya - Date-04/07/2022
    *                     V_1.1 - Modified - Sudheer Kumar Shakya- Date -04/07/2022
    * 
    **/ 
    public override void write(){
        system.debug('Overriden has been performed ');
    }
}